//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoQuestWCF.ServiceReference_TxtPlus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lhc.co.za/webservices/", ConfigurationName="ServiceReference_TxtPlus.SMSSoap")]
    public interface SMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMS(string cellNumber, string text, int applicationID, string userName, string facilityCode, int scheduled, System.DateTime scheduledDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SendSMSAsync(string cellNumber, string text, int applicationID, string userName, string facilityCode, int scheduled, System.DateTime scheduledDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/SendScheduledSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendScheduledSMS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/SendScheduledSMS", ReplyAction="*")]
        System.Threading.Tasks.Task SendScheduledSMSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/Response", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Response(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/Response", ReplyAction="*")]
        System.Threading.Tasks.Task ResponseAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/GetEmailAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetEmailAddress(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/GetEmailAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetEmailAddressAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/GetUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/GetUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUserNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/GetGroupCellInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGroupCellInfo(int GroupID, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lhc.co.za/webservices/GetGroupCellInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetGroupCellInfoAsync(int GroupID, string GroupName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSSoapChannel : InfoQuestWCF.ServiceReference_TxtPlus.SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<InfoQuestWCF.ServiceReference_TxtPlus.SMSSoap>, InfoQuestWCF.ServiceReference_TxtPlus.SMSSoap {
        
        public SMSSoapClient() {
        }
        
        public SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SendSMS(string cellNumber, string text, int applicationID, string userName, string facilityCode, int scheduled, System.DateTime scheduledDateTime) {
            return base.Channel.SendSMS(cellNumber, text, applicationID, userName, facilityCode, scheduled, scheduledDateTime);
        }
        
        public System.Threading.Tasks.Task<int> SendSMSAsync(string cellNumber, string text, int applicationID, string userName, string facilityCode, int scheduled, System.DateTime scheduledDateTime) {
            return base.Channel.SendSMSAsync(cellNumber, text, applicationID, userName, facilityCode, scheduled, scheduledDateTime);
        }
        
        public void SendScheduledSMS() {
            base.Channel.SendScheduledSMS();
        }
        
        public System.Threading.Tasks.Task SendScheduledSMSAsync() {
            return base.Channel.SendScheduledSMSAsync();
        }
        
        public void Response(string xml) {
            base.Channel.Response(xml);
        }
        
        public System.Threading.Tasks.Task ResponseAsync(string xml) {
            return base.Channel.ResponseAsync(xml);
        }
        
        public string GetEmailAddress(string userName) {
            return base.Channel.GetEmailAddress(userName);
        }
        
        public System.Threading.Tasks.Task<string> GetEmailAddressAsync(string userName) {
            return base.Channel.GetEmailAddressAsync(userName);
        }
        
        public string GetUserName() {
            return base.Channel.GetUserName();
        }
        
        public System.Threading.Tasks.Task<string> GetUserNameAsync() {
            return base.Channel.GetUserNameAsync();
        }
        
        public string GetGroupCellInfo(int GroupID, string GroupName) {
            return base.Channel.GetGroupCellInfo(GroupID, GroupName);
        }
        
        public System.Threading.Tasks.Task<string> GetGroupCellInfoAsync(int GroupID, string GroupName) {
            return base.Channel.GetGroupCellInfoAsync(GroupID, GroupName);
        }
    }
}
