//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoQuestForm {
    
    
    public partial class Form_AntimicrobialStewardshipIntervention {
        
        /// <summary>
        /// Body_AntimicrobialStewardshipIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Body_AntimicrobialStewardshipIntervention;
        
        /// <summary>
        /// form_AntimicrobialStewardshipIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form_AntimicrobialStewardshipIntervention;
        
        /// <summary>
        /// HeaderText_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InfoQuestForm.Controls_Header HeaderText_Page;
        
        /// <summary>
        /// NavigationMenu_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InfoQuestForm.Controls_Navigation NavigationMenu_Page;
        
        /// <summary>
        /// ToolkitScriptManager_AntimicrobialStewardshipIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager_AntimicrobialStewardshipIntervention;
        
        /// <summary>
        /// PageUpdateProgress_AntimicrobialStewardshipIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress PageUpdateProgress_AntimicrobialStewardshipIntervention;
        
        /// <summary>
        /// UpdatePanel_AntimicrobialStewardshipIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel_AntimicrobialStewardshipIntervention;
        
        /// <summary>
        /// ImageButton_Logo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ImageButton_Logo;
        
        /// <summary>
        /// Label_Title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_Title;
        
        /// <summary>
        /// Label_SearchHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_SearchHeading;
        
        /// <summary>
        /// Label_InvalidSearchMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_InvalidSearchMessage;
        
        /// <summary>
        /// DropDownList_Facility control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownList_Facility;
        
        /// <summary>
        /// SqlDataSource_ASI_Facility control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_ASI_Facility;
        
        /// <summary>
        /// TextBox_PatientVisitNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox_PatientVisitNumber;
        
        /// <summary>
        /// FilteredTextBoxExtender_PatientVisitNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender FilteredTextBoxExtender_PatientVisitNumber;
        
        /// <summary>
        /// Button_Clear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_Clear;
        
        /// <summary>
        /// Button_Search control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_Search;
        
        /// <summary>
        /// Button_GoToList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_GoToList;
        
        /// <summary>
        /// TableVisitInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableVisitInfo;
        
        /// <summary>
        /// Label_VisitInfoHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VisitInfoHeading;
        
        /// <summary>
        /// Label_VIFacility control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VIFacility;
        
        /// <summary>
        /// Label_VIAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VIAge;
        
        /// <summary>
        /// Label_VIVisitNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VIVisitNumber;
        
        /// <summary>
        /// Label_VIDateAdmission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VIDateAdmission;
        
        /// <summary>
        /// Label_VIName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VIName;
        
        /// <summary>
        /// Label_VIDateDischarge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_VIDateDischarge;
        
        /// <summary>
        /// TableCurrentIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableCurrentIntervention;
        
        /// <summary>
        /// Label_CurrentInterventionHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_CurrentInterventionHeading;
        
        /// <summary>
        /// FormView_AntimicrobialStewardshipIntervention_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView FormView_AntimicrobialStewardshipIntervention_Form;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_InsertByList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_InsertByList;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_InsertNursing5BReason control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_InsertNursing5BReason;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_EditByList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_EditByList;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_EditNursing5BReason control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_EditNursing5BReason;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_ItemNursing5BReason control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_ItemNursing5BReason;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_ItemAntibiotic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_ItemAntibiotic;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_Form;
        
        /// <summary>
        /// TableIntervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableIntervention;
        
        /// <summary>
        /// Label_InterventionHeading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_InterventionHeading;
        
        /// <summary>
        /// Label_TotalRecords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_TotalRecords;
        
        /// <summary>
        /// GridView_AntimicrobialStewardshipIntervention_Intervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView_AntimicrobialStewardshipIntervention_Intervention;
        
        /// <summary>
        /// SqlDataSource_AntimicrobialStewardshipIntervention_Intervention control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_AntimicrobialStewardshipIntervention_Intervention;
        
        /// <summary>
        /// FooterText_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InfoQuestForm.Controls_Footer FooterText_Page;
    }
}
