//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoQuestForm {
    
    
    public partial class Form_PharmacySurveys_LoadedSurveys {
        
        /// <summary>
        /// form_PharmacySurveys_LoadedSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form_PharmacySurveys_LoadedSurveys;
        
        /// <summary>
        /// HeaderText_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InfoQuestForm.Controls_Header HeaderText_Page;
        
        /// <summary>
        /// NavigationMenu_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InfoQuestForm.Controls_Navigation NavigationMenu_Page;
        
        /// <summary>
        /// ToolkitScriptManager_PharmacySurveys_LoadedSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager_PharmacySurveys_LoadedSurveys;
        
        /// <summary>
        /// PageUpdateProgress_PharmacySurveys_LoadedSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress PageUpdateProgress_PharmacySurveys_LoadedSurveys;
        
        /// <summary>
        /// UpdatePanel_PharmacySurveys_LoadedSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel_PharmacySurveys_LoadedSurveys;
        
        /// <summary>
        /// ImageButton_Logo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ImageButton_Logo;
        
        /// <summary>
        /// Label_Title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_Title;
        
        /// <summary>
        /// TableNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableNavigation;
        
        /// <summary>
        /// Label_HeadingNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingNavigation;
        
        /// <summary>
        /// Hyperlink_NavigationSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Hyperlink_NavigationSurveys;
        
        /// <summary>
        /// Hyperlink_NavigationSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Hyperlink_NavigationSections;
        
        /// <summary>
        /// Hyperlink_NavigationQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink Hyperlink_NavigationQuestions;
        
        /// <summary>
        /// Button_CreateSurvey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_CreateSurvey;
        
        /// <summary>
        /// Button_AddSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_AddSection;
        
        /// <summary>
        /// Button_AddQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_AddQuestion;
        
        /// <summary>
        /// Button_AddAnswer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_AddAnswer;
        
        /// <summary>
        /// Button_GoToLoadedSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button_GoToLoadedSurveys;
        
        /// <summary>
        /// DivFormSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivFormSurveys;
        
        /// <summary>
        /// TableFormSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableFormSurveys;
        
        /// <summary>
        /// Label_HeadingFormSurveys control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingFormSurveys;
        
        /// <summary>
        /// FormView_PharmacySurveys_LoadedSurveys_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView FormView_PharmacySurveys_LoadedSurveys_Form;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedSurveys_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedSurveys_Form;
        
        /// <summary>
        /// DivGridSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivGridSections;
        
        /// <summary>
        /// TableGridSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableGridSections;
        
        /// <summary>
        /// Label_HeadingGridSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingGridSections;
        
        /// <summary>
        /// Label_TotalRecords_Sections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_TotalRecords_Sections;
        
        /// <summary>
        /// GridView_PharmacySurveys_LoadedSections_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView_PharmacySurveys_LoadedSections_List;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedSections_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedSections_List;
        
        /// <summary>
        /// DivFormSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivFormSections;
        
        /// <summary>
        /// TableFormSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableFormSections;
        
        /// <summary>
        /// Label_HeadingFormSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingFormSections;
        
        /// <summary>
        /// FormView_PharmacySurveys_LoadedSections_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView FormView_PharmacySurveys_LoadedSections_Form;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedSections_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedSections_Form;
        
        /// <summary>
        /// DivGridQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivGridQuestions;
        
        /// <summary>
        /// TableGridQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableGridQuestions;
        
        /// <summary>
        /// Label_HeadingGridQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingGridQuestions;
        
        /// <summary>
        /// Label_TotalRecords_Questions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_TotalRecords_Questions;
        
        /// <summary>
        /// GridView_PharmacySurveys_LoadedQuestions_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView_PharmacySurveys_LoadedQuestions_List;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_List;
        
        /// <summary>
        /// DivFormQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivFormQuestions;
        
        /// <summary>
        /// TableFormQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableFormQuestions;
        
        /// <summary>
        /// Label_HeadingFormQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingFormQuestions;
        
        /// <summary>
        /// FormView_PharmacySurveys_LoadedQuestions_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView FormView_PharmacySurveys_LoadedQuestions_Form;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_InsertDependencyShowHideLoadedAnswersId_Section control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_InsertDependencyShowHideLoadedAnswersId_Section;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_InsertDependencyShowHideLoadedAnswersId_Question control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_InsertDependencyShowHideLoadedAnswersId_Question;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_InsertDependencyShowHideLoadedAnswersId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_InsertDependencyShowHideLoadedAnswersId;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_EditDependencyShowHideLoadedAnswersId_Section control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_EditDependencyShowHideLoadedAnswersId_Section;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_EditDependencyShowHideLoadedAnswersId_Question control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_EditDependencyShowHideLoadedAnswersId_Question;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_EditDependencyShowHideLoadedAnswersId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_EditDependencyShowHideLoadedAnswersId;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedQuestions_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedQuestions_Form;
        
        /// <summary>
        /// DivGridAnswers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivGridAnswers;
        
        /// <summary>
        /// TableGridAnswers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableGridAnswers;
        
        /// <summary>
        /// Label_HeadingGridAnswers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingGridAnswers;
        
        /// <summary>
        /// Label_TotalRecords_Answers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_TotalRecords_Answers;
        
        /// <summary>
        /// GridView_PharmacySurveys_LoadedAnswers_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView_PharmacySurveys_LoadedAnswers_List;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedAnswers_List control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedAnswers_List;
        
        /// <summary>
        /// DivFormAnswers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivFormAnswers;
        
        /// <summary>
        /// TableFormAnswers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TableFormAnswers;
        
        /// <summary>
        /// Label_HeadingFormAnswers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_HeadingFormAnswers;
        
        /// <summary>
        /// FormView_PharmacySurveys_LoadedAnswers_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView FormView_PharmacySurveys_LoadedAnswers_Form;
        
        /// <summary>
        /// SqlDataSource_PharmacySurveys_LoadedAnswers_Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource_PharmacySurveys_LoadedAnswers_Form;
        
        /// <summary>
        /// FooterText_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InfoQuestForm.Controls_Footer FooterText_Page;
    }
}
